package tech.botworks.electriland.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter // LOMBOK - SHORTCUTS
@Setter // LOMBOK - SHORTCUTS
@NoArgsConstructor // LOMBOK - SHORTCUTS
@Entity
@Table (name="fabrica") // TABLE NAME SMALLCAP BUT SINGULAR
public class Fabrica {
  
  @Id
  @GeneratedValue (strategy = GenerationType.UUID) // UUID AUTOGENERATED
  private String id;

  @Column (name="nombre_fabrica", nullable = false) // DATABASE NOTATION FOR ATTRIBUTE MANDATORY INPUT
  private String nombreFabrica;
}
